### PR TITLE
Adding text of pre and post workshop notification emails

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by rgaiacs** [comment]
@ChristinaLK Thanks very much. Sounds great.

@raynamharris +1 to merge.

**Comment by raynamharris** [comment]
@ChristinaLK yesterday during instructor training it was pointed out that helpers are not invited to these. Should we ask the instructors to reach out to the helpers and invite them to the discussion sessions (either the pre or post or both) or would that be too many people to wrangle?

**Comment by tracykteal** [comment]
I think that might be too many people to wrangle. We should be encouraging the lead instructor of each workshop to hold a pre-workshop call with the other instructors and helpers to go over details and answer any questions. Then they can work out things specific to that workshop.

**Comment by ChristinaLK** [comment]
I think this is a good idea if a) we're able to expand the number of calls at some point in the future and b) there's a more set pattern to accessing instructor training.  
I could see value in having helpers sit in on the debriefing as a way of learning more about the community they could join as instructors - but right now the sessions are full enough as it is and it might be more frustrating than inspiring to think about becoming an instructor, because there isn't a clear route to becoming one (as an individual).

**Comment by raynamharris** [comment]
Thanks @tracykteal @ChristinaLK. I think we are all on the same page.

**Pull request merged**
