### PR TITLE
committee-roles.md: Revise 3-hour rule include teaching

### PR DESCRIPTION
**Pull request by wking**
I've revised my position from #5 to include *both* teaching *and*
committee meetings, so I think we'll all be on board with this
pull-request.  Important points from earlier dicussion in #5
(1,2,3,4,5,6,7):

On Fri, Jan 09, 2015 at 02:27:46PM -0800, Katy Huff wrote (2):
> On Fri, Jan 09, 2015 at 02:07:43PM -0800, W. Trevor King wrote (1):
> > If you instruct a class, I'm certainly not going to get on your
> > case for not putting in an *additional* three hours of volunteer
> > time that week ;).  Or maybe "three hours a week" rolls over?  If
> > so, I think it would be good to make the commitment "12 hours a
> > month" or something else that doesn't roll over.  I don't want all
> > the committee members working like daemons in January and then
> > taking the rest of the year off ;).
>
> I see your complaint.  It does not roll over.  However, it was also
> not meant to be do-or-die.  It was meant to be a goalpost.  I agree
> it should be re-visited if folks are gaming the system or finding it
> too restrictive.  However, we want weekly effort from the committee
> members unless they are on vacation or otherwise.  On the topic of
> instruction.. the explanation is a little simpler.. we made the rule
> that instruction-doesnt-count in order to be explicit about what
> qualified as committee effort and what didn't.  If you teach a lot
> of workshops, great, but you still have to do committee work.
> That's the idea. Hope that helps?

On Fri, Jan 09, 2015 at 04:46:31PM -0800, Greg Wilson wrote (6):
> We're looking for 3 hours/week total from steering committee
> members, not 3 hours on top of committee duties.

So it sounds like the goal is:

* We want three hours a week of anything SWC-related, but don't shirk
  your committee responsibilities.

which is what I've aimed for here.

I've also removed "supporting initiatives prioritized by the Steering
Committee and the Executive Director", because that seems like a
catch-all category that's already handled by "and much more...".  If
it was covering some imporant class (or classes) of activities, I'd
rather list those classes explicitly to give folks a better idea of
what we mean.

Then I wrapped the "fund-raising" entry so it didnt' stick out so far
past the other entries ;).

(1): https://github.com/swcarpentry/board/pull/5#issuecomment-69407414
(2): https://github.com/swcarpentry/board/pull/5#issuecomment-69410381
(3): https://github.com/swcarpentry/board/pull/5#issuecomment-69412275
(4): https://github.com/swcarpentry/board/pull/5#issuecomment-69420926
(5): https://github.com/swcarpentry/board/pull/5#issuecomment-69422871
(6): https://github.com/swcarpentry/board/pull/5#issuecomment-69427061
(7): https://github.com/swcarpentry/board/pull/5#issuecomment-69429866

### CODE REVIEW

**Comment by wking** [comment]
Allowing proxies (#11) would mean that you never have an excuse for shirking committee responsibilities.  I'd append the following to my “As committee members, your committee responsibilities come first…” paragraph:

> If you cannot fulfill your committee responsibilities (regardless of how you schedule your Software Carpentry time), you should appoint a proxy to handle them until you are able to resume them.

I won't bother passing the volunteer-time commitment to the proxy, since I expect proxies to be rare occurences.  If anyone seemed to be abusing their proxy priveleges, I'd call for a new election (#9).

**Comment by r-gaia-cs** [comment]
@wking This looks good to me.

**Comment by katyhuff** [comment]
@r-gaia-cs we will need to vote on this in the meeting. See agenda.

**Comment by katyhuff** [comment]
Hi @wking - The Steering Committee voted to close this one. We want to keep our current 3hrs/week requirement for committee activities only, so I'm going to close this. The reason is, basically, 3hrs/week is barely enough to cover the committee activities we need to lead (includes discussions, initiatives, financial managment, subcommittees, etc.), so we don't want to allow SWC teaching activities to take the place of those important responsibilities.

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 12:44:03PM -0700, Katy Huff wrote:
> The reason is, basically, 3hrs/week is barely enough to cover the
> committee activities we need to lead (includes discussions,
> initiatives, financial managment, subcommittees, etc.), so we don't
> want to allow SWC teaching activities to take the place of those
> important responsibilities.

That's what I was trying to cover with this wording:

  As committee members, your committee responsibilities come first, so
  you shouldn't skip meetings or avoid posting meeting minutes because
  you've already put in three hours of workshop instruction in a given
  week.

The idea was “handle your committee responsibilities, and if that
takes less than three hours in a given week, fill up to at least three
by picking from this list…”.

I just force-pushed a ‘instruciton’ → ‘instruction’ typo fix, taking
the tip from 0f893af to 67eac1e.

**Comment by katyhuff** [comment]
I think what we're saying is, the need for SC work is infinite. If the current committee challenges they are are responsible for take less than 3 hours in a given week, committee members should strive to use that time to address the multitudinous other challenges facing the committee.

**Comment by wking** [comment]
On Thu, Mar 12, 2015 at 04:01:19PM -0700, Katy Huff wrote:
> I think what we're saying is, the need for SC work is infinite. If
> the current committee challenges they are are responsible for take
> less than 3 hours in a given week, committee members should strive
> to use that time to address the multitudinous other challenges
> facing the committee.

If there are other committee-side tasks that are not their
responsibility (e.g. working on the budget for
non-finance-subcommittee members), I'd certainly encourage the other
committe members to chip in.  But if someone has discharged their
personal committee obligations for the week in less than three hours
and also taught at a workshop that week, I wouldn't mind them leaving
the budget issues to the finance subcommittee (for that week).  If
someone consistently avoids helping by teaching workshops, the other
committee members can always explicitly assign them more
committee-side responsibilities.  That seems clearer to me than
permanently tagging one foundation-serving activity as not counting.

**Comment by wking** [comment]
On Sat, Jan 10, 2015 at 12:47PM -0700, W. Trevor King wrote:
> So it sounds like the goal is:
>
> * We want three hours a week of anything SWC-related, but don't
>   shirk your committee responsibilities.
>
> which is what I've aimed for here.

It seems like I missed the mark here.  Maybe we're shooting for [1]:

* We want three hours a week of SCF committee duties, and aren't
  speaking about other SWC activity.

This gets me back to my initial confusion about active vs. passive
committees (based on [2], see [3] and later comments for discussion).
Re-reading the blog post [2] and getting Katy's clarification [1], it
seems like the distinction between active and passive is either in the
expected time committee activity or in the extension of “committee
activity” to cover non-meeting actions like “supporting initiatives
prioritized by the Steering Committee and the Executive Director”.

I still think it's clearer and equally useful draw the box around “SWC
time” than to draw a box around “Steering-Committee-related time”, but
I'll work up a pull request to clarify the board's current position
(as I understand it).

[1]: https://github.com/swcarpentry/board/pull/32/files#r27418636
[2]: http://software-carpentry.org/blog/2014/12/plans-for-2015-mentorship-and-assessment.html
[3]: https://github.com/swcarpentry/board/pull/5#issuecomment-69422871

**Comment by katyhuff** [comment]
I honestly think this is very much clarified already in the main sentence of the "Participation" section which you find issue with. It says:

Participation must include 3 hours per week of Software Carpentry Foundation volunteer time.

They key word there is an always has been "Foundation"

**Comment by katyhuff** [comment]
Note that I tried to clarify this before, in the last paragraph of my comment here:
https://github.com/swcarpentry/board/pull/5#issuecomment-69420926

**Comment by wking** [comment]
On Mon, Mar 30, 2015 at 03:07:25PM -0700, Katy Huff wrote:
> Participation must include 3 hours per week of Software Carpentry
> Foundation volunteer time.
> 
> They key word there is an always has been "Foundation"

I consider SCF activity to be all things Software Carpentry (which
does include teaching workshops).  Changing those words to “… of
Steering-Committee-related volunteer time” would help draw the
distinction between subcommittee time, etc., and teaching.  I expect
there are some other bits that could be reworded to make the
distinction clearer as well, but I haven't had time yet to review the
text with this in mind (and likely won't for the next few weeks).  My
comment here was mostly a note so I don't forget the new (to me)
interpretation so we can avoid rehashing previously-clarified
confusion.

**Comment by gvwilson** [comment]
HI @wking,
I think the wording is plenty clear enough given good will, and no 
refinement to the wording will make up for its absence, so I vote for 
wrapping this thread.
Thanks,
@gvwilson

**Comment by katyhuff** [comment]
Please feel free to make any PRs. 
Maybe, in terms of the meaning of "Foundation", it will help if you go to this page: http://software-carpentry.org/scf/index.html . Check out, in particular, the list of things SCF is supposed to do "In aid of these goals".

**Comment by wking** [comment]
On Mon, Mar 30, 2015 at 03:15:35PM -0700, Katy Huff wrote:
> Note that I tried to clarify this before, in the last paragraph of my comment here:
> https://github.com/swcarpentry/board/pull/5#issuecomment-69420926

Yeah, but I was still thinking that the committee work was covered by
the committee responsibilities, and that the 3-hour rule must apply to
something else ([1], and my “it sounds like the goal is…” comment from
the start of this PR).  In fact, when I responded in [1], I still
thought it had to be so different that the committee time shouldn't
count.  When I realized that committee time should count, I revised my
position and opened this issue [2].  Not that I realize *only*
committee time is intended to count (your “NOT our SWC duties” turned
on that lightbulb), I'm shifting my approach again.

Anyhow, I apologize for being slow on the uptake, but I think that the
active/passive lense I was reading through was too different from
reality for me to understand the rule as it's written now.  Maybe I'm
especially dense and nobody else will have the same confusion, but I'd
expect there is some room to rephrase this rule in a way that's
clearer for everybody.

[1]: https://github.com/swcarpentry/board/pull/5#issuecomment-69422871
[2]: https://github.com/swcarpentry/board/pull/5#issuecomment-69471378

**Comment by katyhuff** [comment]
Thanks @wking . I would never describe you as dense. Any suggestions welcome.

**Pull request closed without merging**
