### PR TITLE
Update subcommittees

### PR DESCRIPTION
**Pull request by r-gaia-cs**

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Mar 15, 2015 at 03:38:13PM -0700, Raniere Silva wrote:
>   * Update subcommittees

Ah, is this syncing from swcarpentry/site#872 and
swcarpentry/site#878?  It looks like it's changing more than just
that.  Anyhow, I'm happy this file is getting updated, and I think we
should just leave the blog post in swcarpentry/site alone (e.g. we
don't update our students-taught graphs in old blog posts after new
numbers come in ;).

**Comment by r-gaia-cs** [comment]
> Ah, is this syncing from swcarpentry/site#872 and
> swcarpentry/site#878?

Yes.

> It looks like it's changing more than just that. 

I sorted the list of members because it was bugging me. =)

> Anyhow, I'm happy this file is getting updated, and I think we
> should just leave the blog post in swcarpentry/site alone

We will leave the blog post alone. I just want to give credit to people that will be at the subcommittees in this first round.

**Comment by wking** [comment]
On Sun, Mar 15, 2015 at 04:51:47PM -0700, Raniere Silva wrote:
> I just want to give credit to people that will be at the
> subcommittees in this first round.

Absolutely.  Maybe a link from the blog post to [1]?  Something like:

   We are therefore thrilled to announce a set of community-driven
   subcommittees aimed at initiatives essential to the Software
   Carpentry Foundation.  This post reflects the subcommittee
   membership around the time it was posted.  For details on the
   current subcommittees and their membership, see [1].  For past
   members, see [2].

Although we might want an official past-members page instead of
linking folks to the Git history.  And we can leave off the
past-members part until we actually have past members ;).

[1]: https://github.com/swcarpentry/board/blob/master/subcommittees/subcommittees.md
[2]: https://github.com/swcarpentry/board/commits/master/subcommittees/subcommittees.md

**Comment by r-gaia-cs** [comment]
> Although we might want an official past-members page instead of
> linking folks to the Git history.  And we can leave off the
> past-members part until we actually have past members ;).

+1 to leave off until we actually have past members.

**Comment by r-gaia-cs** [comment]
@katyhuff Can you merge this? This will close #28 and #29.

**Comment by r-gaia-cs** [comment]
@katyhuff I'm merging this.

**Comment by katyhuff** [comment]
Thanks!

**Pull request merged**
