### PR TITLE
subcommittees: Restructure for per-subcommittee directories

### PR DESCRIPTION
**Pull request by wking**
Also for task forces.  This streamlines the generic docs and listings, and pushes the per-subcomittee (or task force) details down into their own separate area.  With a specific area, the per-subcomittee information may be more likely to stay up to date (by avoiding [diffusion of responsibility][1]) and there is more space for useful information like links to blogs, mailing lists, repositories, etc.

I've attempted to fill in GitHub usernames and some of this auxiliary project information to the best of my knowledge, but it's a lot of shifting around information I'm not particularly familiar with, so I may have gotten some things wrong.

Related to #144, although this PR is about putting a maintainable framework in place, and not about updating the information to match reality.

[1]: https://en.wikipedia.org/wiki/Diffusion_of_responsibility

### CODE REVIEW

**Comment by raynamharris** [comment]
Thank @wking . I think this is a very good suggestion. When the original committees were first set up, it made sense to have all the details listed in one readme, but as we grow, I think keeping the specifics in committee- or task force- specific directories makes more sense. Also, this provides a better frame work for transitioning from what to do after the committee has been proposed with an issue.

**Comment by raynamharris** [comment]
@wking I want to merge this, but I changed something so now I have a conflict. Help?

**Comment by wking** [comment]
On Mon, Dec 19, 2016 at 02:39:07PM -0800, Rayna M Harris wrote:
> @wking I want to merge this, but I changed something so now I have a
> conflict. Help?

Rebased around #153 and subsequent commits with 8052eb2 → b55bdff.
You probably want to look over the updated
TaskForces/2017-CarpentryCon/README.md to make sure my updated version
looks like what you want.

**Comment by raynamharris** [comment]
Thanks! Yes, this has the update I wanted.

**Pull request merged**
