### PR TITLE
Added a privacy notice to be included in the etherpad at debriefing session

### PR DESCRIPTION
**Pull request by ttimbers**
@r-gaia-cs Please make any changes you see fit. I tried to make this clear and short as possible in the hopes that it will be read by everybody. 

In response to your email you sent to the instructors and mentoring lists, Trevor King suggested that when a private topic emerges we do discuss it at the debrief, but have the instructor state that they would like to speak off the record and we refrain from taking notes until we are back on the record. I did not include this in my brief privacy note because I think we as a mentorship committee should discuss it further. Your thoughts?

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@ttimbers Thanks. It looks great.

> In response to your email you sent to the instructors and mentoring lists, Trevor King suggested that when a private topic emerges we do discuss it at the debrief, but have the instructor state that they would like to speak off the record and we refrain from taking notes until we are back on the record. I did not include this in my brief privacy note because I think we as a mentorship committee should discuss it further. Your thoughts?

We are using a public etherpad which means that what someone write on it is more or less public.
We can discuss it futher in our next meeting.

**Comment by wking** [comment]
On Sat, Mar 21, 2015 at 06:59:04PM -0700, Raniere Silva wrote:
> > In response to your email you sent to the instructors and
> > mentoring lists, Trevor King suggested that when a private topic
> > emerges we do discuss it at the debrief, but have the instructor
> > state that they would like to speak off the record and we refrain
> > from taking notes until we are back on the record. I did not
> > include this in my brief privacy note because I think we as a
> > mentorship committee should discuss it further. Your thoughts?
> 
> We are using a public etherpad which means that what someone write
> on it is more or less public.  We can discuss it futher in our next
> meeting.

I have no stake in the outcome here, since I'm not involved in these
debriefing sessions.  But are they just via Etherpad?  Or is there
another channel, like the conference calls we use for the group
meetings (or used to use, I haven't been able to make one of those
meetings since we left Mozilla).  In any case, I expect we can publish
instructions suggesting people say “this is off the record, but…” for
sensitive material.  The *instructions* wouldn't be sensitive, so they
could go in the Etherpad.  The person sharing the sensitive
information would be publishing it over a (more) secure channel (like
the conference call's audio), and not over an insecure channel (like
the Etherpad).  So I don't see “Etherpad is public” as really
mattering (unless it is the only channel available).

Of course, I personally see little reason for off-the-record
discussion (see #20), so the “this is all public, don't share
sensitive information” message that landed with this PR works for me
:).

**Comment by r-gaia-cs** [comment]
> But are they just via Etherpad?  Or is there another channel,
> like the conference calls we use for the group
> meetings (or used to use, I haven't been able to make one of those
> meetings since we left Mozilla).

The last debriefing sessions we used Google Hangouts
because (1) the number of participants in less than 10 [1],
(2) it allows video for almost any OS
and (3) is cheap to everyone.

> The *instructions* wouldn't be sensitive, so they
> could go in the Etherpad.  The person sharing the sensitive
> information would be publishing it over a (more) secure channel (like
> the conference call's audio), and not over an insecure channel (like
> the Etherpad).

If someone asked in the audio to let something off-the-record
we will do it but by default we can add to the etherpad information
from the audio.

[1]: https://support.google.com/plus/answer/1216376?hl=en

**Comment by wking** [comment]
On Sun, Mar 22, 2015 at 06:00:03AM -0700, Raniere Silva wrote:
> > The *instructions* wouldn't be sensitive, so they could go in the
> > Etherpad.  The person sharing the sensitive information would be
> > publishing it over a (more) secure channel (like the conference
> > call's audio), and not over an insecure channel (like the
> > Etherpad).
> 
> If someone asked in the audio to let something off-the-record we
> will do it but by default we can add to the etherpad information
> from the audio.

That makes sense to me.  You could weaken the wording from this PR to
express that with something like:

  Anything stated verbally or written down in the Etherpad during
  Instructor debriefing sessions will be considered public and may be
  used at a later time point in a public blog post unless the speaker
  explicitly states that the material is off the record when
  delivering it.

Also, is the confidential@ email just for the mentoring sub-committee?
It's a pretty generic name, so my guess is that it goes to the
executive director who may, at his/her discretion, share it with other
members of the steering committee.  But maybe it just goes to the
steering committee?  Or to the steering committee and the executive
director?  Or also to other admins?  In any case, if the scope is any
larger than the mentoring sub-committee, I'd write a generic blurb
explaining the confidential@ address somewhere on
software-carpentry.org, and then link from the first paragraph of this
blurb to the external confidential@ blurb.  Something like:

  If you want to share some confidential material without involving
  the other debriefing participants, you can always email
  [confidential@software-carpentry.org][confidential].

  [confidential]: http://software-carpentry.org/…somewhere…

**Comment by karinlag** [comment]
On 22/03/15 02:59, Raniere Silva wrote:

> We are using a public etherpad which means that what someone write on it
> is more or less public.
> We can discuss it futher in our next meeting.

I think having this complete shutdown also on oral communication during 
the meeting may close down communication a bit too much. How about 
having an add-on saying that we suppose anything said orally is also for 
public consumption, but open up for them saying things "off-the-record" 
as long as they actually tell us so.

But, as Raniere said - next meeting :)

K

**Pull request merged**
