### PR TITLE
WIP: subcommittees: Add lesson-infrastructure and lesson-maintainer

### LINKED ISSUE #154: Proposed revision for Lesson Maintainer subcommittee
**Proposed Revision for Lesson Maintainer Subcommittee**

This proposal follows the expectations/subheadings outlined in the [subcommittee proposal instructions](https://github.com/swcarpentry/board/blob/master/subcommittees/proposal_instructions.md), and is being submitted in conjunction with a proposal to create a separate Lesson Infrastructure  #subcommittee (#155).

**Current description of lessons subcommittee**: [website](http://software-carpentry.org/join/subcom/maintainers/), [board repo](https://github.com/swcarpentry/board/blob/master/maintainers.md), also related to [old lesson organization committee](https://github.com/swcarpentry/board/tree/master/subcommittees/lessons)

**Specific goals**
Each subcommittee member is expected to maintain their assigned lesson repository

**Steps**

- Review and merge PRs for assigned repo (both content and templates)
- Guide discussions around development and evolution of content for assigned lessons
- Manage issues for assigned repo
- Review communications from Lesson Infrastructure Subcommittee and implement guidelines as recommended

**Timeline**

- Maintenance of assigned repository is ongoing
- Lesson Infrastructure meets quarterly
- Maintainers welcome to attend
- Maintainers receive summary of meeting

**Measuring success**

- Continuation of functional, continually improved lessons
- Increased participation from community in lesson maintenance

**Members**

- http://software-carpentry.org/lessons/ 
- http://www.datacarpentry.org/lessons/  

**Budget**
N/A

### LINKED ISSUE #155: Proposal for Lesson Infrastructure subcommittee
**Proposal for Lesson Infrastructure Subcommittee**

This proposal follows the expectations/subheadings outlined in the [subcommittee proposal instructions](https://github.com/swcarpentry/board/blob/master/subcommittees/proposal_instructions.md), and is being submitted in conjunction with a proposal to revise the lesson maintainers (#154).

**Current description of lessons subcommittee**: [website](http://software-carpentry.org/join/subcom/maintainers/), [board repo](https://github.com/swcarpentry/board/blob/master/maintainers.md), also related to [old lesson organization committee](https://github.com/swcarpentry/board/tree/master/subcommittees/lessons)

**Specific goals**

- Manage lesson release process and coordinate lesson releases
- Group decision-making for any changes that will affect more than one lesson
- This applies to lessons officially described as “supported” by the Carpentries
- Maintenance of the following general repositories: 
1. [styles](https://github.com/swcarpentry/styles)
2. [lesson-example](https://github.com/swcarpentry/lesson-example)
3. [workshop-template](https://github.com/swcarpentry/workshop-template)
- Not responsible for decisions about development or adoption of new lessons, as this falls under the [lesson incubation process](https://software-carpentry.org/lessons/incubation/)

**Steps**

- Review issues and PRs for repositories described above
- Determine workflows for general issues related to lesson maintenance
- Communicate with all maintainers about changes to general repositories and common workflows

**Timeline**
Meet quarterly

**Measuring success**

- Continuation of functional, continually improved lesson framework
- Increased participation from community in lesson maintenance

**Members**
Kate Hertweck
Naupaka Zimmerman
Maneesha Sane
Raniere Silva
Rémi Emonet
Greg Wilson
Tracy Teal
Gabriel Devenyi

**Budget**
N/A

### PR DESCRIPTION
**Pull request by wking**
Documenting #154 and #155, which were both approved in the SWC Steering Committee's [2017-01-04 motion 3][3].

There are still some FIXMEs here (e.g. the infrastructure mailing list and Steering Committee liaisons).

I'm also not sure how these are supposed to straddle SWC and DC (andother carpentries?).  The language in #154 made it feel like the maintainer subcommittee was supposed to be pan-carpentry, but that would make liaisons and accountability less clear until we establish procedures for shared subcommittees.

Fixes #154.
Fixes #155.
Related to #144 (deprecates the old lessons subcommittee).

[1]: https://github.com/swcarpentry/board/issues/154
[2]: https://github.com/swcarpentry/board/issues/155
[3]: https://github.com/swcarpentry/board/blob/45f7e9606e58c85cc9fbf3f534416b39fd74a7a2/minutes/minutes-2017-01-04.md#motion-2017-01-043

### CODE REVIEW

**Comment by wking** [comment]
CC @k8hertweck.  And if a SWC GitHub admin could add @swcarpentry/lesson-infrastructure and @swcarpentry/lesson-maintainer teams, that would make it easier to ping related folks (although it gives us one more place to keep the memberships up to date).

I'm pulling the infrastructure membership from the recent email thread.  If anyone is on that thread and *not* a member (maybe @jduckles?), let me know and I'll take them off the list.

**Comment by wking** [comment]
In today's meetings (#174), @tracykteal asked for docs around the maintainer-LGTM approach.  For the OCI, those docs are [here][1] and [here][2].  There is also a separate track for changes more significant than your average pull request (e.g. cutting releases or changing project rules) [here][3].  If we want to take this approach for the lesson-infrastructure repositories, we would need:

* Clear lists of maintainers for each repo (which is a good idea anyway).
* Documentation that explains how maintainers vote on issues/PRs (in issue comments, or with [GitHub's reviews][4], or whatever).
* (optional) tooling to collect those votes and decide when our passing conditions are satisfied.

[1]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/MAINTAINERS_GUIDE.md#how-are-decisions-made
[2]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/MAINTAINERS_GUIDE.md#who-decides-what
[3]: https://github.com/opencontainers/project-template/blob/16f84db17e49bcafbef9209a8e90185b7df7f884/GOVERNANCE.md
[4]: https://help.github.com/articles/about-pull-request-reviews/

**Comment by k8hertweck** [comment]
Sorry for the lag on this, and thanks so much for the work, @wking. As for your concerns/notes above:

- These are pan-carpentries in the sense that we're interesting in consolidating effort. This will likely be clarified and made more explicit in coming months. 
- We're discussing GitHub management issues at our next Steering Committee meeting, and I'll add some notes about whether we feel teams for subcommittees would help or hinder.
- [This comment](https://github.com/swcarpentry/board/pull/171#issuecomment-278415915) is awesome and helps clarify some ways we can make these decisions across our communities. Many thanks!
- I can be added as the SC liaison for both subcommittees.

Apart from that, what else needs to be completed before merging?

**Comment by raynamharris** [comment]
@wking @k8hertweck Can this be merged?

**Pull request merged**
