### PR TITLE
adds minutes from last two meetings.

### PR DESCRIPTION
**Pull request by katyhuff**

### CODE REVIEW

**Comment by gvwilson** [comment]
Both look good to me - shall I merge?

**Comment by katyhuff** [comment]
Thanks!

On Thu, Feb 12, 2015 at 9:34 AM, Greg Wilson <notifications@github.com>
wrote:

> Both look good to me - shall I merge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/board/pull/16#issuecomment-74114713>.
>



-- 
http://katyhuff.github.com

**Comment by r-gaia-cs** [comment]
:+1: to merge.

**Comment by tracykteal** [comment]
+1

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 09:29:22AM -0800, Katy Huff wrote:
>   * adds minutes from last two meetings.

While we're catching up, maybe merge #14 too?

Also:

  +-   Advisory Council roles (NCH)
  +    -   See https://github.com/swcarpentry/board_pvt/pull/51

Is linking to private content.  Is that intentional?  In this
repository I'd expect a public description of the referenced
discussion, but no link to the private discussion.

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 09:29:22AM -0800, Katy Huff wrote:
> + - NPCH: explanation of ground rules
> +   - use of voice + etherpad
> +   - voting procedures

Can we record the voting procedures in a public location?  See also
#10.

**Pull request merged**
