### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by raynamharris**
@ChristinaLK Here is my first draft for the readme.md page that can serve as a temp webpage. Here's my rationale

Purpose/scope: @rgaiacs  wrote the first sentence a long time ago in a blog community call. I made up the second sentence. I think this should be a broad overview of what we do.

What we do: This is the main piece where people can see what we do. I don't know if there is enough detail here or not, but its a start. I thought we could give a shout out to the old activities, but I don't know if that is necessary. Should we add the old lesson-specific discussion sections?

Join us: This was also edited from something @rgaiacs wrote a while back.  I estimated the 2-8 hour a month thing. Also, I'm not sure how many things we want people to host... or if you want to add other things to this "what we do section"

### CODE REVIEW

**Comment by raynamharris** [comment]
@ChristinaLK Do you think this is okay to accept and merge?  I'd like to have it in place by Monday if possible because I think there's a good chance people will be interested in seeing what the mentoring committee has been up to...

**Comment by tracykteal** [comment]
@raynamharris this looks great. It does a good job of laying out what the mentoring subcommittee does and what people's role would be when they join. It seems ready to go, but maybe get Marian's view, since she's just joining, so has a fresh perspective on what she would have liked to see.

**Comment by ChristinaLK** [comment]
Yes, this looks good to me!  I was going to email around to newer mentoring committee members and ask for their opinions and forgot. There was a Dave on the call two weeks ago who was also new to the committee...

**Comment by rgaiacs** [comment]
Looks good. :sparkles:

**Comment by raynamharris** [comment]
Okay. I'll go ahead and merge. Any edits can be added later. Thanks!

**Pull request merged**
