### PR TITLE
executive-director: Put in charge of SC resources

### PR DESCRIPTION
**Pull request by wking**
E.g. this makes it more obvious the the executive branch is in charge
of moderating discussion lists as it sees fit.  These responsibilities
don't talk about delegation vs. direct action by the Executive
Director, but I expect delegation is fine as long as the buck stops
with the ED.

Spun off from #114.

### CODE REVIEW

**Comment by BillMills** [comment]
I'm -1 to this; language that explicitly gives the ED the right to intervene as they see fit is fine, but it is just not good management to dump too many disparate responsibilities on one employee. This creates major distractions from top-line responsibilities that the ED should be free to focus on.

**Comment by wking** [comment]
On Wed, May 11, 2016 at 12:44:21PM -0700, Bill Mills wrote:
> but it is just not good management to dump too many disparate
> responsibilities on one employee.

All executive responsibilities belong to the Executive Director.  They
are free to deputize as they see fit.  The alternative is to create a
parallel structure for managing resources (a Resource Director?) with
the RD also answering to the Steering Committee, and I don't see how
that would help.

**Comment by BillMills** [comment]
> (a Resource Director?) 

Finding bandwidth for community management is already in the works; what form that takes is TBD, but there is a difference between giving the ED the authority to arbitrate, and saying it is his primary responsibility to do so. This is well intentioned, but IMO does not pay enough attention to the extremely finite nature of our ED's time.

Furthermore, the SC resolved earlier this week to have all staff draft job descriptions for themselves; suggestions always welcome, but the intent is to let them lead on these documents. Also, changing someone's responsibilities mid-contract is just not cool.

**Comment by wking** [comment]
On Wed, May 11, 2016 at 12:56:20PM -0700, Bill Mills wrote:
> Finding bandwidth for community management is already in the works;
> what form that takes is TBD…

I suggest the community manager fall under the ED instead of answering
to the SC directly.  And I suggest that specifing and filling that
position fall solely under the ED (with the SC's usual ED oversight
and advisory role).  Putting executive control for community resources
outside of ED control makes for lots of fuzzy boundaries that I'd
rather avoid ;).

“… there is a difference between giving the ED the authority to
arbitrate, and saying it is his primary responsibility to do so.”

This is the sort of fuzzy authority-without-responsibility boundary
I'm worried about.  The buck should clearly stop with someone.

And yeah, I agree that this is not something to put on @jduckles
without his consent.  This sort of addresses your “let them lead”
point.  I'm clearly not in a position to enforce anything here, and am
just floating ideas that the SC and ED can pick up if they like them
;).

**Comment by BillMills** [comment]
> I suggest the community manager fall under the ED instead of answering to the SC directly. And I suggest that specifing and filling that position fall solely under the ED (with the SC's usual ED oversight and advisory role). Putting executive control for community resources outside of ED control makes for lots of fuzzy boundaries that I'd rather avoid ;).

+1 to all of this - I think what we're disagreeing on how the word 'responsible' is to be interpreted. You seem to be using it in the sense of oversight, which I am 100% on board with; but without added qualifiers, to be responsible for something means you are actually going to personally do it, which is how this PR reads to me. What if we changed your text to "Responsible for overseeing the management and maintenance of all..."

**Comment by wking** [comment]
On Wed, May 11, 2016 at 01:12:18PM -0700, Bill Mills wrote:
> What if we changed your text to "Responsible for overseeing the
> management and maintenance of all..."

As I mentioned briefly in my commit message and PR topic [1], I think
*all* ED responsibilities are open to delegation.  What sort of
distinction do you see between “responsible for” and “responsible for
overseeing”?

[1]: https://github.com/swcarpentry/board/pull/115#issue-154325201

**Comment by BillMills** [comment]
> What sort of distinction do you see between “responsible for” and “responsible for overseeing”?

The crucial distinction is in the implied expectations. 'responsible for x' can be easily interpreted as the ED will be doing x themself; 'responsible for overseeing x' suggests the ED is expected to appoint a mod(s) and be available to drop the hammer in rare, extenuating circumstances when the mod(s) need help. Put another way, my language indicates that this responsibility falls on the 'Office of the ED', rather than on the ED themself, if that makes sense.

**Comment by jiffyclub** [comment]
I feel like a delegation responsibility is already implied in this document. For example, we have the line "Responsible for effective administration of Software Carpentry operations", but we don't expect the ED to run operations themselves. Most of that is delegated to our paid and volunteer admins, members of the SC, mentoring committee, etc.

**Comment by wking** [comment]
On Wed, May 11, 2016 at 04:51:15PM -0700, Bill Mills wrote:
> The crucial distinction is in the implied expectations.

How does 965a0d8 look to you?

**Comment by wking** [comment]
On Wed, May 11, 2016 at 04:58:31PM -0700, Matt Davis wrote:
> I feel like a delegation responsibility is already implied in this
> document.

That's where I started [1], but there's no harm in spelling it out if
it helps clear up confusion like [2].

[1]: https://github.com/swcarpentry/board/pull/115#issue-154325201
[2]: https://github.com/swcarpentry/board/pull/115#issuecomment-218575688

**Comment by BillMills** [comment]
> How does 965a0d8 look to you?

much better, fit to merge at @jduckles' approval. Contracts are no place for implication :)

**Comment by wking** [comment]
On Wed, May 11, 2016 at 06:05:00PM -0700, Bill Mills wrote:
> … fit to merge at @jduckles' approval.

Probably needs a SC vote as well, since this is about the SC ↔ ED
relationship.

**Comment by gvwilson** [comment]
Who should this one be assigned to?

**Comment by rgaiacs** [comment]
@JasonJWilliamsNY I believe that we never vote on this. Can we add to the next meeting?

**Comment by raynamharris** [comment]
As far as I can tell, this suggestion is no longer directly relevant to this repor. However, @jduckles @tracykteal @k8hertweck may want to think about these tasks as part of the merger job descriptions.

**Comment by wking** [comment]
On Thu, Dec 14, 2017 at 08:47:13PM +0000, Rayna M Harris wrote:
> As far as I can tell, this suggestion is no longer directly relevant
> to this repo…

Is there a new location for it?  The closest thing I can find to a
Carpentries Executive Director policy is [1,2], which don't explicitly
talk about delegating ED powers.

[1]: https://github.com/carpentries/2017Merger/blob/f540c9fc95d7fe73038415467e462daedd83c5eb/RFCs/RFC4.md
[2]: https://github.com/carpentries/2017Merger/blob/f540c9fc95d7fe73038415467e462daedd83c5eb/infrastructure/overview.md

**Pull request closed without merging**
