### PR TITLE
Amendment for Steering Committee transition procedures.

### PR DESCRIPTION
**Pull request by k8hertweck**
This PR includes the current public-facing governance rules with the addition of the following proposed amendment:

"Following an election, the new Steering Committee will meet jointly with the previous Steering Committee for no less than 60 days. For meetings during the first 30 first days, the new SC will not have voting privileges. After 30 days, voting privileges are transferred to the new SC."

 The community election for this amendment will be held October 10-14.

### CODE REVIEW

**Comment by karinlag** [comment]
This is not the text we voted on. Also, I think it is significantly less clear than the text we actually passed. The first impression that I get is that the new sc has no voting privileges for the 60 days. Yes, the next sentence does counter that, but by then I already have my hackles up.

i.e. -1 from me.

**Comment by BillMills** [comment]
Yep I'm with @karinlag; the last two sentences need to be something like "the outgoing SC retains sole voting rights for the first 30 days; those voting privileges transfer to the incoming SC after the first 30 days."

Which begs the question - what exactly starts the 60 day timer?

**Comment by rgaiacs** [comment]
> This is not the text we voted on.

@karinlag This is exact the text that we vote.

> Following an election, the new Steering Committee will meet jointly with the previous Steering Committee for no less than 60 days. For meetings during the first 30 first days, the new SC will not have voting privileges. After 30 days, voting privileges are transferred to the new SC.

About

> the last two sentences need to be something like "the outgoing SC retains sole voting rights for the first 30 days; those voting privileges transfer to the incoming SC after the first 30 days."

@swcarpentry/board We can vote to change it if need.

**Comment by BillMills** [comment]
@rgaiacs no, no need to re-vote; the already approved text is perfect, but it's not what's presented in the top post here. If we stick to the text as approved then there's no problem.

**Comment by karinlag** [comment]
On 05.09.2016 18:46, Bill Mills wrote:
> @rgaiacs <https://github.com/rgaiacs> no, no need to re-vote; the
> already approved text is perfect, but it's not what's presented in the
> top post here. If we stick to the text as approved then there's no problem.


As bill says: we have a text we have approved. Let's just stick that in 
there.

K

**Comment by k8hertweck** [comment]
You all are correct; I made an error when entering the amendment text, which is why I'm so grateful for proofreaders! I've updated the opening comment above as well as [blog post](https://github.com/swcarpentry/website/pull/505) accordingly (along with other suggestions by Raniere).

**Comment by k8hertweck** [comment]
Any further comments on this or the blog post? I need to remove extraneous comments on this thread, and give the OK for releasing the blog post in the next day or so.
@BillMills @karinlag @rgaiacs @raynamharris @weaverbel @JasonJWilliamsNY

**Comment by raynamharris** [comment]
Okay to merge @k8hertweck ?

**Pull request merged**
