### PR TITLE
governance: Adapt Steering Committee rules for low-candidate elections

### PR DESCRIPTION
**Pull request by wking**
This would make @rgaiacs' proposal from [here][1] lawful.

[1]: https://github.com/swcarpentry/board/blob/13037e523e1ea5c7b1612582ff252b37f92018a1/minutes/minutes-2017-01-04.md#motion-2017-01-041

### CODE REVIEW

**Comment by wking** [comment]
And the rules for changing the charter are just “[Steering Committee majority vote][1]”.

[1]: https://github.com/swcarpentry/board/blob/13037e523e1ea5c7b1612582ff252b37f92018a1/governance.md#amendment

**Comment by karinlag** [comment]
I as a SC member, and somebody who will be on the next one, am uncomfortable with this one. No matter the number of people running we should have the vote. Otherwise it would just seem like the board came to be by magic. 

If nothing else, we should have an election so that people know that the SC _is_ elected, and by extension that they could run next year.

**Comment by wking** [comment]
On Mon, Jan 16, 2017 at 09:51:44AM -0800, karinlag wrote:
> If nothing else, we should have an election so that people know that
> the SC _is_ elected…

There are a number of election-related blog posts [1] (which will
become more obvious once swcarpentry/website#641 lands).  And you
posts about “last call for candidates” and “we're skipping the actual
vote because there aren't enough candidates”, so I don't think we need
an actual vote to help discovery.

[1]: https://software-carpentry.org/blog/categories/#election-2017

**Comment by rgaiacs** [comment]
@wking Thanks for the pull request. The Steering Committee considered my motion unlawful because we already announced elections and change the rules during it could look unfair. The same reason applies for Karin's counter motion. We briefly discuss what to do for future elections but we decided to hold all motion proposals related with election until the next Steering Committee is in place.

**Comment by wking** [comment]
On Mon, Jan 16, 2017 at 01:55:55PM -0800, Raniere Silva wrote:
> We briefly discuss what to do for future elections but we decided to
> hold all motion proposals related with election until the next
> Steering Committee is in place.

This makes sense.  The next Steering Committee can pick this up when
they take the reins, or maybe it can get picked up during the hand-off
period, since there are four members who will be rolling over.

**Comment by raynamharris** [comment]
I believe this issue has been resolved.

**Comment by wking** [comment]
While I'm in favor of this change (obviously ;), you need a
steering-committee majority vote to change the rules [1].  Did that
happen?  I can't turn it up grepping through minutes/.

[1]: https://github.com/swcarpentry/board/blame/438582f6af780268467aef02680da26e709abf30/governance.md#L209-L213

**Pull request merged**
