### PR TITLE
Workflow for mentoring subcommittee

### PR DESCRIPTION
**Pull request by rgaiacs**
This had https://gist.github.com/BillMills/8b9d43addfb98d63d50c as start point. Thanks to @BillMills.

### CODE REVIEW

**Comment by gvwilson** [comment]
The diagram has "Metoring" in the legend rather than "Mentoring"

**Comment by rgaiacs** [comment]
@raynamharris Do you want to close this?

**Comment by raynamharris** [comment]
Hmm. We should think about whether or not we want to revise this given that now we just offer a single instructor discussion session. It could be nice to have a concept map to include in the instructor training lesson material, but I don't know. Thoughts @BillMills @ChristinaLK @gvwilson

**Comment by BillMills** [comment]
@raynamharris this map captured the moment last year, when we were still refactoring how all our scrums fit together - I think we have moved past this particular map at the moment. Per @gvwilson's classic advice of getting everyone in a meeting to draw a concept map of what the meeting is about, I'd love to see someone else on mentoring take a swing at this; lately I've been pinch-hitting debriefs no one else has time for, and that's all; I'd love for the rest of the team to take point on what Mentorship's grand plan is.

**Comment by ChristinaLK** [comment]
Here's what an updated version might look like: 
http://pages.cs.wisc.edu/~ckoch5/mentoring_map.pdf
Boxes are what we're doing, clouds are big-picture goals.

**Comment by karinlag** [comment]
On 14/09/16 17:36, Christina Koch wrote:
> Here's what an updated version might look like:
> http://pages.cs.wisc.edu/~ckoch5/mentoring_map.pdf
> <http://pages.cs.wisc.edu/%7Eckoch5/mentoring_map.pdf>
> Boxes are what we're doing, clouds are big-picture goals.

I think this one captures things quite nicely!

Karin

**Comment by rgaiacs** [comment]
@raynamharris Can you create a new pull request to replace this one since it is out of date. Thanks!!!

**Comment by raynamharris** [comment]
Closing due to inactivity.

**Pull request closed without merging**
